### ISSUE TITLE
Getting error Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by ebinxavier** [ngfelixl/nodeplotlib#20]
Sometimes I am getting this error randomly. I have checked the size of data array, all are same sized.

> const json = require('./bt-json');
    const plots=[];
    json.forEach(jsonI=>{
        const points = jsonI.series.points;
        plots.push({x:points.map(point=>moment(point[0])),y:points.map(point=>point[1]),name:jsonI.series.name}); 
    })
    nodePlotLib.plot(plots);

**Comment by ngfelixl** [comment]
Hi! thanks for your issue submission. Can you provide what exactly `plots` is?

**Comment by conundrumer** [comment]
I'm also getting this error when I try to plot traces with a lot of points, 30913 to be exact. I think I encountered `ERR_CONTENT_LENGTH_MISMATCH`. I can plot half that amount though.

**Comment by ngfelixl** [comment]
Thanks for letting me know. Does it happen only for a specific plot-type or for more than one plots-type?

**Comment by mitsos1os** [comment]
This must be hapenning due to the server closing [here](https://github.com/ngfelixl/nodeplotlib/blob/b65337e29e338b7415735c419a4cc914745c897c/src/server.ts#L111) right after sending the response.
So in case of large reponses, all data do not have the time necessary to be sent to the client.

**Comment by Moumouls** [comment]
Okay i encountered this issue, i pushed the fix with the failing test: https://github.com/ngfelixl/nodeplotlib/pull/45
Hope it helps and could be merged asap 🙂

**Comment by mitsos1os** [comment]
Good job @Moumouls!
