### ISSUE TITLE
How to save plot as image file?

### ISSUE THREAD

**Issue by DeusNexus** [ngfelixl/nodeplotlib#21]
Hi, I want to save the plot to an image file (jpg/png) and not let it open the browser every time. Is this possible?

**Comment by ngfelixl** [comment]
Hi @DeusNexus, this is currently not possible. Please propose a feature request containing details about how exactly you would like to use it. Thanks and cheers! :)

**Comment by filipmacek** [comment]
Is this feature maybe possible or.
I would be really helpful to save as file and maybe send to s3
