### ISSUE TITLE
Barmode is not working

### ISSUE THREAD

**Issue by JohnsonLinnn** [ngfelixl/nodeplotlib#36]
**Describe the bug**
Hi, I've tried to change the bar mode of a bar chart, and no matter what I've done, the bar mode seems to always set to default, which is 'group'.
I've tried the same configuration with Plotly node.js, and the output graph does respond to the change in configuration.

Here's the code I used with ploty nodejs
```
const plotly = require('plotly')("___________", "________________")
let trace1 = {
  x: ['giraffes', 'orangutans', 'monkeys'],
  y: [20, 14, 23],
  name: 'SF Zoo',

  type: 'bar'
};

let trace2 = {
  x: ['giraffes', 'orangutans', 'monkeys'],
  y: [12, 18, 29],
  name: 'LA Zoo',
  type: 'bar'
};
let data = [trace1, trace2];
let layout = {barmode: "stack"};
let graphOptions = {layout: layout, filename: "simple-node-example", fileopt: "overwrite"};
plotly.plot(data, graphOptions, function (err, msg) {
      console.log(msg);
});
```
Here's the code I used with nodeplotlib
```
const plt = require('nodeplotlib');
let trace1 = {
    x: ['giraffes', 'orangutans', 'monkeys'],
    y: [20, 14, 23],
    name: 'SF Zoo',
    type: 'bar'
  };
  
let trace2 = {
    x: ['giraffes', 'orangutans', 'monkeys'],
    y: [12, 18, 29],
    name: 'LA Zoo',
    type: 'bar'
  };
let data = [trace1, trace2];
let layout = {barmode: 'stack'};
let graphOptions = {layout:layout,filename: "date-axes", fileopt: "overwrite"};

plt.plot(data, graphOptions, function (err, msg) {
     console.log(msg);
 });
```
**To Reproduce**
1. add username and API key to the plot nodejs code
2. run both codes on node js 

**Expected behavior**
The graph shows on ploty chart studio have the bar chart in 'stack' layout, 
but the graph shows from nodeplotlib shows the default 'group' layout

**Screenshots**
The results from ploty node js
<img width="860" alt="Screen Shot 2021-01-03 at 3 21 50 AM" src="https://user-images.githubusercontent.com/67190402/103470460-d4fea200-4d72-11eb-8dbc-2d4cefeaa082.png">

The results from nodeplotlib
<img width="1386" alt="Screen Shot 2021-01-03 at 3 19 23 AM" src="https://user-images.githubusercontent.com/67190402/103470431-7e916380-4d72-11eb-99ce-6de3a80cf057.png">

**Desktop (please complete the following information):**
dependencies:
"nodeplotlib": "^0.6.5",
"plotly": "^1.0.6",
"plotly.js": "^1.58.4"

Thanks for helping!

**Comment by ngfelixl** [comment]
Hi @JohnsonLinnn, thank you for reporting. I think the problem is due to a not up-to-date plotly version. I will work on an update and check if the barmode will work. Thank you for submitting the reproduction steps.

**Comment by ngfelixl** [comment]
@JohnsonLinnn you need to pass in the `layout` as the second parameter to the plot function and not the `graphOptions`.

```typescript
[...]
let layout = {barmode: 'stack'};
let graphOptions = {layout,filename: "date-axes", fileopt: "overwrite"};

plt.plot(data, layout);
```

Then you should be able to see the plots as stacked bars.

**Comment by JohnsonLinnn** [comment]
@ngfelixl it's working now! thanks for helping!!
