### ISSUE TITLE
Scatterplot shows a line graph

### ISSUE THREAD

**Issue by nathanbabcock** [ngfelixl/nodeplotlib#60]
Scatterplots should have only points, no lines. There is no separate option for a line graph.

**Comment by InsideBSITheSecond** [comment]
this is normal.
see this codepen for usage of the scatter graph: https://codepen.io/pen/?&prefill_data_id=6f1e424f-7ef3-4ece-a844-73dff02f2c6a

**Comment by nathanbabcock** [comment]
In nodeplotlib it's not possible to get a scatterplot (points only) with no lines. I guess the bindings to the underlying plotly haven't been written for that particular option.

**Comment by InsideBSITheSecond** [comment]
as I just linked you, it is.
https://streamable.com/f3dmzi

**Comment by nathanbabcock** [comment]
`mode: markers` was what I was missing. Thanks! 👍

**Comment by ngfelixl** [comment]
@nathanbabcock sorry for the late response. Nodeplotlib uses the exact Plotly API. There are no internal processes that modify the `plot` and the `layout` data.
